#server:
#  port: 8001
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.xuecheng.entities    # 所有Entity别名类所在包
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://182.61.17.59:3306/clouddb01?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8            # 数据库名称
#    username: root
#    password: 123456
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200      # 等待连接获取的最大超时时间
#  rabbitmq:
#    host: 182.61.17.59
#    port: 5672
#    username: guest
#    password: guest
#  cloud:
#    stream:
#      bindings:
#        myInput:
#          destination: minestream
#          group: stream
#          consumer:
#            partitioned: true  #启动分区
#        myOutput:
#          destination: minestream
#          producer:
#            partitionKeyExpression: payload
#            partitionCount: 1
#      instance-count: 1
#      instance-index: 0
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  redis:
#    host: 182.61.17.59
#    port: 6379
#  data:
#    mongodb:
#      uri: mongodb://182.61.17.59:27017/mydb
#info:
#  app.name: atguigu-microservicecloud
#  company.name: www.atguigu.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
#feign:
#  hystrix:
#    enabled: true
#logging:
#  level:
#    root: debug
