spring:
  sleuth:
    enabled: false
  application:
    name: framework-zipkin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 4b85b7e2-f42e-4aa3-91a0-da2a4f0c671f
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: 4b85b7e2-f42e-4aa3-91a0-da2a4f0c671f
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://106.13.16.189:3306/zipkin_config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
server:
  port: 8081
zipkin:
  storage:
    type: mysql
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
      web:
        exposure:
          include: '*'